#############################################################################
# Makefile for building: musicplayer.app/Contents/MacOS/musicplayer
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  musicplayer.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile musicplayer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DHAVE_GETTIMEOFDAY -D__MACOSX_CORE__ -D__LITTLE_ENDIAN__ -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -w -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -w -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../stk/include -I../stk/src/include -I/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt55/5.5.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt55/5.5.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang -F/usr/local/Cellar/qt55/5.5.1/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = musicplayer1.0.0
DISTDIR = /Users/ajercaianu/Fac/PS/proiect/musicplayer/.tmp/musicplayer1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt55/5.5.1/lib Release/* -lpthread -framework CoreAudio -framework CoreFoundation -framework CoreMIDI -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = delayeffect.cpp \
		audioplayer.cpp \
		mainwindow.cpp \
		play.cpp moc_mainwindow.cpp
OBJECTS       = delayeffect.o \
		audioplayer.o \
		mainwindow.o \
		play.o \
		moc_mainwindow.o
DIST          = /usr/local/Cellar/qt55/5.5.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/c++11.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/warn_off.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/lex.prf \
		musicplayer.pro delayeffect.h \
		audioplayer.h \
		mainwindow.h delayeffect.cpp \
		audioplayer.cpp \
		mainwindow.cpp \
		play.cpp
QMAKE_TARGET  = musicplayer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = musicplayer.app/Contents/MacOS/musicplayer

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-w



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d musicplayer.app/Contents/MacOS/ || mkdir -p musicplayer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: musicplayer.pro /usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt55/5.5.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/c++11.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/warn_off.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt55/5.5.1/mkspecs/features/lex.prf \
		musicplayer.pro \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt55/5.5.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt55/5.5.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile musicplayer.pro
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcollision.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcollision_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3drenderer.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_3drenderer_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/c++11.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/warn_off.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt55/5.5.1/mkspecs/features/lex.prf:
musicplayer.pro:
/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt55/5.5.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt55/5.5.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile musicplayer.pro

qmake_all: FORCE

musicplayer.app/Contents/PkgInfo: 
	@test -d musicplayer.app/Contents || mkdir -p musicplayer.app/Contents
	@$(DEL_FILE) musicplayer.app/Contents/PkgInfo
	@echo "APPL????" > musicplayer.app/Contents/PkgInfo
musicplayer.app/Contents/Resources/empty.lproj: 
	@test -d musicplayer.app/Contents/Resources || mkdir -p musicplayer.app/Contents/Resources
	@touch musicplayer.app/Contents/Resources/empty.lproj
	
musicplayer.app/Contents/Info.plist: 
	@test -d musicplayer.app/Contents || mkdir -p musicplayer.app/Contents
	@$(DEL_FILE) musicplayer.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.musicplayer,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,musicplayer,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang/Info.plist.app >musicplayer.app/Contents/Info.plist

all: Makefile \
		musicplayer.app/Contents/PkgInfo \
		musicplayer.app/Contents/Resources/empty.lproj \
		musicplayer.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents delayeffect.h audioplayer.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents delayeffect.cpp audioplayer.cpp mainwindow.cpp play.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r musicplayer.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qwidget.h \
		mainwindow.h
	/usr/local/Cellar/qt55/5.5.1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt55/5.5.1/mkspecs/macx-clang -I/Users/ajercaianu/Fac/PS/proiect/musicplayer -I/Users/ajercaianu/Fac/PS/proiect/musicplayer -I/Users/ajercaianu/Fac/PS/proiect/stk/include -I/Users/ajercaianu/Fac/PS/proiect/stk/src/include -I/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt55/5.5.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt55/5.5.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/usr/local/Cellar/qt55/5.5.1/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

delayeffect.o: delayeffect.cpp ../stk/include/FileWvIn.h \
		../stk/include/WvIn.h \
		../stk/include/Stk.h \
		../stk/include/FileRead.h \
		../stk/include/RtAudio.h \
		audioplayer.h \
		delayeffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delayeffect.o delayeffect.cpp

audioplayer.o: audioplayer.cpp ../stk/include/FileWvIn.h \
		../stk/include/WvIn.h \
		../stk/include/Stk.h \
		../stk/include/FileRead.h \
		../stk/include/RtAudio.h \
		audioplayer.h \
		delayeffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioplayer.o audioplayer.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qwidget.h \
		audioplayer.h \
		../stk/include/FileWvIn.h \
		../stk/include/WvIn.h \
		../stk/include/Stk.h \
		../stk/include/FileRead.h \
		../stk/include/RtAudio.h \
		delayeffect.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

play.o: play.cpp ../stk/include/FileWvIn.h \
		../stk/include/WvIn.h \
		../stk/include/Stk.h \
		../stk/include/FileRead.h \
		../stk/include/RtAudio.h \
		mainwindow.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qwidget.h \
		audioplayer.h \
		delayeffect.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/QtWidgets \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qerrormessage.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qfontdialog.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qwizard.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcolumnview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdirmodel.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qheaderview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlistview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtableview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtreeview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtreewidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qactiongroup.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgesture.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qshortcut.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtooltip.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdrawutil.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qproxystyle.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstyle.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstylefactory.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstyleoption.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstylepainter.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcolormap.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcompleter.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qscroller.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qundogroup.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qundostack.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qundoview.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qabstractslider.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdial.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qfocusframe.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmdiarea.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qrubberband.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qsizegrip.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qspinbox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qsplitter.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtabbar.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtabwidget.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtoolbox.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		/usr/local/Cellar/qt55/5.5.1/lib/QtWidgets.framework/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o play.o play.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

